/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as http from "../http.js";
import type * as mealPlans from "../mealPlans.js";
import type * as quotas from "../quotas.js";
import type * as recipes from "../recipes.js";
import type * as settings from "../settings.js";
import type * as spoonacular from "../spoonacular.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  http: typeof http;
  mealPlans: typeof mealPlans;
  quotas: typeof quotas;
  recipes: typeof recipes;
  settings: typeof settings;
  spoonacular: typeof spoonacular;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
